apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#nameSuffix: -dev
namespace: kustom-prod
commonLabels:
  oper_env: prod
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/revisionHistoryLimit
        value: 20
    target:
      kind: Deployment
      labelSelector: "app=apiimg"
  - path: deployment.yaml
    target:
      kind: Deployment
      labelSelector: "app=apiimg"

images:
- name: quay.io/rhdevelopers/bgd:default
  newTag: latest