apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustom-default
resources:
- rbac.yaml
- deployment.yaml
- service.yaml
- route.yaml

# secretGenerator:
# - name: quay-secret
#   files:
#   - .dockerconfigjson=dockerconfigjson
#   type: "kubernetes.io/dockerconfigjson"


commonLabels:
  oper_env: default
  app: apiimg

#namePrefix: apiimg-
#nameSuffix: -default
